const FilterConstants = {
  UPDATE_BOUNDS: "UPDATE_BOUNDS",
  UPDATE_PRICE: "UPDATE_PRICE",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  UPDATE_REVIEW_COUNT: "UPDATE_REVIEW_COUNT",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  UPDATE_LOCATION: "UPDATE_LOCATION"
};

module.exports = FilterConstants;
