module.exports = [
  {name: "Soul Food"},
  {name: "Southern Food"},
  {name: "Japanese"},
  {name: "Asian"},
  {name: "African"},
  {name: "Russian"},
  {name: "South American"},
  {name: "Mexican"},
  {name: "Hispanic"},
  {name: "Korean"},
  {name: "Chinese"},
  {name: "American"},
  {name: "Italian"},
  {name: "Irish"},
  {name: "British"},
  {name: "Ethiopian"},
  {name: "Fast Food"},
  {name: "hamburger"},
  {name: "burger"},
  {name: "pasta"},
  {name: "ramen"},
  {name: "sushi"},
  {name: "bibimbap"},
  {name: "taco"},
  {name: "burrito"},
  {name: "steak"},
  {name: "chicken"},
  {name: "lamb"},
  {name: "bbq"},
  {name: "catering"},
  {name: "lunch"},
  {name: "fried chicken"},
  {name: "Arab"},
  {name: "Armenian"},
  {name: "Assyrian"},
  {name: "Balochi"},
  {name: "Berber"},
  {name: "Buddhist"},
  {name: "Bulgarian"},
  {name: "Cajun"},
  {name: "Circassian"},
  {name: "French"},
  {name: "Greek"},
  {name: "Jewish"},
  {name: "Kurdish"},
  {name: "Malayali"},
  {name: "Louisiana Creole"},
  {name: "Malay cuisine"},
  {name: "Persian cuisine"},
  {name: "Punjabi"},
  {name: "Rajasthani"},
  {name: "Russian"},
  {name: "Sami"},
  {name: "Sindhi"},
  {name: "Tatar"},
  {name: "Turkish"},
  {name: "Yamal"},
  {name: "Zanzibari"},
  {name: "South Indian"},
];
