FAKEREVIEWS = [
  "Never tell me the odds!",
  "Well, you said you wanted to be around when I made a mistake." "…I take it back!",
  "You do have your moments. Not many, but you have them.",
  "I know.",
  "Ben! I can be a Jedi. Ben, tell him I’m ready! (Thumps head on ceiling.) Ow!",
  "I’m not afraid.",
  "You will be.",
  "Now, witness the power of this fully operational battle station.",
  "…Scoundrel. I like that.",
  "I have a bad feeling about this.",
  "Hmm! Adventure. Hmmpf! Excitement. A Jedi craves not these things.",
  "Who’s the more foolish; the fool, or the fool who follows him?",
  "That… is why you fail.",
  "It’s worse.",
  "That’s no moon.",
  "Sorry about the mess.",
  "Ready are you? What know you of ready? For eight hundred years have I trained Jedi. My own counsel will I keep on who is to be trained. A Jedi must have the deepest commitment, the most serious mind. This one, a long time have I watched. All his life has he looked away… to the future, to the horizon. Never his mind on where he was. …Hmm? On what he was doing.",
  "If they follow standard Imperial procedure, they’ll dump their garbage before they go to light-speed. Then we just… float away." "…With the rest of the garbage.",
  "Laugh it up, fuzzball!",
  "I never doubted you! Wonderful!",
  "You will never find a more wretched hive of scum and villainy. …We must be cautious.",
  "Would somebody get this big walking carpet out of my way?!",
  "No reward is worth this.",
  "I happen to like… nice men.",
  "We would be honored if you would join us.",
  "So what I told you was true… from a certain point of view." "…A certain point of view?!",
  "Your weapon… you will not need it.",
  "…Boring conversation anyway. Luke! We’re gonna have company!",
  "…I think I just blasted it.",
  "That’s not true.",
  "That’s impossible.",
  "Search your feelings.",
  "I’ll never join you.",
  "He certainly has courage." "...Yeah, but what good is that if he gets himself killed?",
  "…You’ve failed, your highness. I am a Jedi, as my father was before me." "…So be it, Jedi.",
  "Only at the end do you realize the power of the Dark Side.",
  "It’s not impossible. I used to bullseye womp rats in my T-16 back home, they’re not much bigger than two meters.",
  "Awww! But I was going into Tosche Station to pick up some power converters!!!",
  "IT’S A TRAP.",
  "But how could they be jamming us if they don’t know… that we’re… coming?",
  "He is as clumsy as he is stupid!",
  "Strike me down, and I will become more powerful than you could possibly imagine.",
  "STAY ON TARGET.",
  "…It’s not fair! They promised me they fixed it! It’s not my fault!",
  "You know, that little droid is going to cause me a lot of trouble." "…Oh, he excels at that, sir.",
  "If you’re saying that coming here was a bad idea, I’m starting to agree with you.",
  "For over a thousand generations, the Jedi were the guardians of peace and justice in the Old Republic — before the dark times. Before the Empire.",
  "Shut him up or shut him down.",
  "Give yourself to the Dark Side. It is the only way you can save your friends. Yes; your thoughts betray you. Your feelings for them are strong. Especially for your… sister. So, you have a twin sister. Your feelings have now betrayed her too. Obi-Wan was wise to hide her from me. Now, his failure is complete. If you will not turn to the Dark Side… then perhaps she will…",
  "I find your lack of faith disturbing.",
  "Uh, we had a slight weapons malfunction, but uh… everything’s perfectly all right now. We’re fine. We’re all fine here now, thank you. (Winces.) Uh, how are you?",
  "You are a member of the rebel alliance, and a traitor.",
  "The circle is now complete.",
  "Hey, I think my eyes are getting better. Instead of a big dark blur, I see a big bright blur." "…There’s nothing to see. I used to live here, you know." "…You’re gonna die here, you know. Convenient.",
  "Why, you stuck up, half-witted, scruffy-looking Nerf herder.",
  "Ungh. And I thought they smelled bad on the outside.",
  "Would it help if I got out and pushed?!! ...It might!",
  "You don’t have to do this to impress me.",
  "Try not. Do… or do not. There is no try.",
  "Luminous beings are we, not this crude matter.",
  "All too easy.",
  "How you doin’, Chewbecca? Still hanging around with this loser?",
  "I assure you, Lord Vader. My men are working as fast as they can." "…Perhaps I can find new ways to motivate them.",
  "Apology accepted, Captain Needa.",
  "You’ll find I’m full of surprises!",
  "Yeah… you’re a real hero.",
  "A Jedi Knight? Jeez, I’m out of it for a little while, everyone gets delusions of grandeur!",
  "I’m Luke Skywalker? I’m here to rescue you!" "…You’re who?",
  "Everything is proceeding as I have foreseen.",
  "Bounty hunters! We don’t need this scum.",
  "Boba Fett? Boba Fett? Where?",
  "Keep your distance, Chewie, but don’t, y’know, look like you’re keeping your distance. (Grumbled questioning bark.) …I don’t know. Fly casual.",
  "What have you done?! I’m BACKWARDS.",
  "You will find that it is you who are mistaken… about a great many things.",
  "Only a master of evil, Darth.",
  "We seem to be made to suffer. It’s our lot in life.",
  "We have — ungh! — powerful friends. You’re going to regret this." "…I’m sure.",
  "It’s against my programming to impersonate a deity.",
  "These aren’t the droids you’re looking for.",
  "Aren’t you a little short for a Stormtrooper?",
  "Wait. I know that laugh…",
  "This is some rescue!",
  "He’s the brains, sweetheart!",
  "You are unwise to lower your defenses!",
  "Boy, it’s lucky you have these compartments!",
  "Travelling through hyperspace ain’t like dustin’ crops, boy!",
  "They’re getting closer. …Oh yeah? Watch this. (…Long pause — the engine sputters and dies.)",
  "Great, kid. Don’t get cocky.",
  "You would prefer another target? A military target? Then name the system!",
  "R2-D2, you know better than to trust a strange computer!",
  "Luke, you switched off your targeting computer — what’s wrong?" "…Nothing! I’m all right.",
  "So, what do you think? You think a princess and a guy like me–",
  "I want them alive — no disintegrations!",
  "I’ve just made a deal that will keep the Empire out of here forever.",
  "I have you now!",
  "I saw… a city in the clouds.",
  "Told you I did. Reckless is he. …Now, matters are worse.",
  "That boy is our last hope.",
  "…No. There is another.",
  "A boy's best friend is his mother.",
"A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.",
"A martini. Shaken, not stirred.",
"After all, tomorrow is another day!",
"All right, Mr. DeMille, I'm ready for my close-up.",
"As God is my witness, I'll never be hungry again.",
"Attica! Attica!",
"Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!",
"Bond. James Bond.",
"Carpe diem. Seize the day, boys. Make your lives extraordinary.",
"Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!",
"E.T. phone home.",
"Elementary, my dear Watson.",
"Fasten your seatbelts. It's going to be a bumpy night.",
"Forget it, Jake, it's Chinatown.",
"Frankly, my dear, I don't give a damn.",
"Gentlemen, you can't fight in here! This is the War Room!",
"Get your stinking paws off me, you damned dirty ape.",
"Go ahead, make my day.",
"Greed, for lack of a better word, is good.",
"Hasta la vista, baby.",
"Hello, gorgeous.",
"Here's Johnny!",
"Here's looking at you, kid.",
"Houston, we have a problem.",
"I am big! It's the pictures that got small.",
"I feel the need—the need for speed!",
"I have always depended on the kindness of strangers.",
"I love the smell of napalm in the morning.",
"I see dead people.",
"I want to be alone.",
"I'll be back.",
"I'll get you, my pretty, and your little dog too!",
"I'll have what she's having.",
"I'm as mad as hell, and I'm not going to take this anymore!",
"I'm gonna make him an offer he can't refuse.",
"I'm the king of the world!" ,
"I'm walking here! I'm walking here!",
"If you build it, he will come.",
"Is it safe?",
"It's alive! It's alive!",
"Keep your friends close, but your enemies closer.",
"La-dee-da, la-dee-da.",
"Life is a banquet, and most poor suckers are starving to death!",
"Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!",
"Listen to them. Children of the night. What music they make.",
"Louis, I think this is the beginning of a beautiful friendship.",
"Love means never having to say you're sorry.",
"Made it, Ma! Top of the world!",
"Mama always said life was like a box of chocolates. You never know what you're gonna get.",
"May the Force be with you.",
"Mother of mercy, is this the end of Rico?",
"Mrs. Robinson, you're trying to seduce me. Aren't you?",
"My mother thanks you. My father thanks you. My sister thanks you. And I thank you.",
"My precious.",
"No wire hangers, ever!",
"Nobody puts Baby in a corner.",
"Of all the gin joints in all the towns in all the world, she walks into mine.",
"Oh, Jerry, don't let's ask for the moon. We have the stars.",
"Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.",
"One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know.",
"Open the pod bay doors, HAL.",
"Plastics.",
"Play it, Sam. Play 'As Time Goes By.'",
"Rosebud.",
"Round up the usual suspects.",
"Sawyer, you're going out a youngster, but you've got to come back a star!",
"Say 'hello' to my little friend!",
"Shane. Shane. Come back!",
"Show me the money!",
"Snap out of it!",
"Soylent Green is people!",
"Stella! Hey, Stella!",
"Tell 'em to go out there with all they got and win just one forthe Gipper.",
"The stuff that dreams are made of.",
"There's no crying in baseball!",
"There's no place like home.",
"They call me Mister Tibbs!",
"They're here!",
"Today, I consider myself the luckiest man on the face of the Earth.",
"Toga! Toga!",
"Toto, I've got a feeling we're not in Kansas anymore.",
"Wait a minute, wait a minute. You ain't heard nothin' yet!",
"We rob banks.",
"We'll always have Paris.",
"Well, here's another nice mess you've gotten me into!",
"Well, nobody's perfect.",
"What a dump.",
"What we've got here is failure to communicate.",
"Who's on first?",
"Why don't you come up sometime and see me?",
"Yo, Adrian!",
"You can't handle the truth!",
"You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am, let's face it.",
"You had me at 'hello.'",
"You know how to whistle, don't you, Steve? You just put your lips together and blow.",
"You talkin' to me?",
"You're gonna need a bigger boat.",
"You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?",
"Surely you can't be serious. I am serious...and don't call me Shirley."
]
